import { Word } from "./word";

export const WordList:Word[]=[

    {wordId:1,wordName:"able",wordDescription:"yapabilen"},
    {wordId:2,wordName:"about",wordDescription:"hakkında"},
    {wordId:3,wordName:"above",wordDescription:"üstünde"},
    {wordId:4,wordName:"across",wordDescription:"karşısında"},
    {wordId:5,wordName:"act",wordDescription:"hareket, eylem"},
    {wordId:6,wordName:"back",wordDescription:"arka"},
    {wordId:7,wordName:"bad",wordDescription:"kötü"},
    {wordId:8,wordName:"ball",wordDescription:"top"},
    {wordId:9,wordName:"bank",wordDescription:"banka"},
    {wordId:10,wordName:"base",wordDescription:"temel"},
    {wordId:11,wordName:"came",wordDescription:"geldi"},
    {wordId:12,wordName:"can",wordDescription:"yapabilmek"},
    {wordId:13,wordName:"cannot",wordDescription:"yapamamak"},
    {wordId:14,wordName:"can't",wordDescription:"yapamamak"},
    {wordId:15,wordName:"capital",wordDescription:"başken"},
    {wordId:16,wordName:"dance",wordDescription:"dans etmek"},
    {wordId:17,wordName:"dark",wordDescription:"karanlık"},
    {wordId:18,wordName:"day",wordDescription:"gün"},
    {wordId:19,wordName:"dead",wordDescription:"ölü"},
    {wordId:20,wordName:"deal",wordDescription:"anlaşma"},
    {wordId:21,wordName:"early",wordDescription:"erken"},
    {wordId:22,wordName:"ear",wordDescription:"kulak"},
    {wordId:23,wordName:"earth",wordDescription:"toprak, dünya"},
    {wordId:24,wordName:"east",wordDescription:"doğu"},
    {wordId:25,wordName:"easy",wordDescription:"kolay"},
    {wordId:26,wordName:"increase",wordDescription:"yükselmek"},
    {wordId:27,wordName:"Indian",wordDescription:"Hindistanlı"},
    {wordId:28,wordName:"indicate",wordDescription:"göstermek"},
    {wordId:29,wordName:"industry",wordDescription:"endüstri"},
    {wordId:30,wordName:"information",wordDescription:"bilgi"},
    {wordId:1,wordName:"natural",wordDescription:"doğal"},
    {wordId:1,wordName:"near",wordDescription:"yanında"},
    {wordId:1,wordName:"necessary",wordDescription:"gerekli"},
    {wordId:1,wordName:"need",wordDescription:"ihtiyaç duymak"},
    {wordId:35,wordName:"never",wordDescription:"asla"},
        
	    
]