import { QuintessentialWords } from "./quintessential";

export const QuintessentialWordsList:QuintessentialWords[]=[


    {word:'Dünyada iki farklı insan var, bilmek isteyenler ve inanmak isteyenler.',author:'Friedrich Nietzsche'},
    {word:'Engelsiz bir yol bulursanız, muhtemelen hiçbir yere gitmez.',author:'Frank A.Clark'},
    {word:'İntikam ve aşkta, kadın insandan daha barbardır.',author:'Friedrich Nietzsche'} ,
    {word:'İçinde dans eden bir yıldız doğurmak için kaosun olması gerekir.',author:'Friedrich Nietzsche'},
    {word:'Zihin paraşüt gibidir.Açık değilse işe yaramaz. ',author:'Frank Zappa'},
    {word:'Karakter kolay ve sessizce geliştirilemez.Sadece acı ve deneyimiyle ruh güçlenir.',author:''},
    {word:'Hayat bir bisiklete binmek gibidir.Dengenizi korumak için hareket etmeye devam etmelisiniz.',author:'Albert Einstein'},
    {word:'Akıl, doldurulacak bir gemi değil, yakılacak bir ateştir.',author:'Plutarkhos'},
    {word:'Kalbini değiştirerek hayatını değiştirirsin.',author:'Max Lucado'},
    {word:'Gücüm onun gücü kadar, çünkü kalbim saf.',author:'Alfred Lord Tennyson'},
    {word:'Bir şeyi sevmenin yolu, bunun kaybolabileceğini fark etmektir. ',author:'Gilbert K. Chesterton'},
    {word:'Dünyayı değiştirmenize gerek yok; kendini değiştirmek zorundasın.',author:'Miguel Angel Ruiz'},
    {word:'Affetmek geçmişi değiştirmez ama geIeceğin önünü açar. ',author:'-PauI Boese'},
    {word:'Beni mahveden şey; bana yaIan söyIemiş oIman değiI, sana bir daha inanmayacak oImamdır.',author:'Victor Hugo'} ,
    {word:'İnsanIar seninIe konuşmayı bıraktığında, arkandan konuşmaya başIarIar.',author:'-PabIo Neruda'} ,
    {word:'Öğrenmek, akıntıya karşı yüzmek gibidir iIerIeyemediğiniz taktirde geriIersiniz. ',author:'– Çin Atasözü'},
    {word:'Yapmacık oIup seviImektense, kendim oIup nefret ediImeyi tercih ederim.',author:'-Tom Robbins'} ,
    {word:'Senin için yaprakIarını kopardığım papatyaIardan özür diIedim dün gece. “HakIısınız dedim, ne sevdiği beIIi, ne sevmediği.',author:'-P.Neruda'} ,
    {word:'Geleceğimin tam olarak nasıl olacağını hala bilmiyorum ama, bildiğim bir şey var ki içinde sen yoksun.',author:'- Post Grad'} ,
    {word:'Hayattan korkmayın çocuklar; iyi ve doğru bir şeyler yaptığınız zaman hayat öyle güzel ki. ',author:'-  Dostoyevski'},
    {word:'Aslında hayatın en güzel anı; her şeyden vazgeçtiğinde, seni hayata bağlayan birinin olduğunu düşündüğün andır. ',author:'-Balzac'},
    {word:'Sen benim hiçbir şeyimsin, yabancı bir şarkı gibi yarım, yağmurlu bir ağaç gibi ıslak, hiç kimse misin bilmem ki nesin?',author:' -Attila İlhan'},
    {word:'Hayatta bir gayesi olmayan insanlar, bir nehir üzerinde akıp giden saman çöplerine benzerler; onlar gitmezler, ancak suyun akışına kapılırlar. ',author:'-Seneca'},
    {word:'Ve uyandığınızda ilk hatırladığınız yine “o” olur, nasıl ki uyumadan önce o olduysa! ',author:'- Kahraman.Tazeoğlu'},
    {word:'Politika politikacılara bırakılmayacak kadar önemli bir konudur.',author:'- Charles De Gaulle'} ,
    {word:'Metodu olan topal, metotsuz koşandan daha çabuk ilerler.',author:'- Francis Bacon'} ,
    {word:'Mutluluğu tatmanın tek çaresi, onu paylaşmaktır. ',author:'- Byron'},
    {word:'Kadın kocasını daha az sevmeli, fakat daha çok anlamalı; erkek, karısını daha çok sevmeli, fakat anlamaya çalışmamalıdır.',author:' - Oscar Wilde'},
    {word:'İnsan aklındakilerle gündüzleri, yüreğindekiyle geceleri uğraşıyormuş.',author:'- Can Yücel'} ,
    {word:'İyi olduğunuz için herkesin size adil davranmasını beklemek, vejetaryan olduğunuz için boğanın saldırmayacağını düşünmeye benzer. ',author:'- Dennis Wholey'},
    {word:'Mutluluğun sırrı özgürlüktür.Ve özgürlük sırrı cesarettir.',author:'Thucydides'} ,
    {word:'Bir rüya büyü ile gerçek olmaz; ter, kararlılık ve sıkı çalışma gerektirir.',author:'Colin Powell'},
    {word:'Yapabileceğiniz en büyük macera, hayallerinizin hayatını yaşamaktır.',author:'Oprah Winfrey'},
    {word:'Bilgelik, herhangi bir zenginlikten daha önemlidir.',author:'Sofokles'},
    {word:'Kendisine itaat etmek isteyen, nasıl emredeceğini bilmesi gerekir.',author:'Niccolo Machiavelli'} ,
    {word:'Dünü kurtarmak bizim elimizde değildir, fakat yarını kazanmak ya da kaybetmek bizim elimizdedir.',author:''},
    {word:'Yanında aptal bir kadın olan bir sürü zeki adam görürsünüz ama yanında aptal bir adam olan zeki kadın kolay kolay göremezsiniz. ',author:'- E.Jong'},
    {word:'Hayat geç kalanları hiç affetmez.',author:'- Gorbachov'} ,
    {word:'Bir gün hayatına birisi girecek ve o gün, daha öncekilerle neden işlerin yürümediğini anlayacaksın.',author:' - Elif Şafak'},
    {word:'Mutluluğun değerini, onu kaybettikten sonra anlarız.',author:'- Plautus'} ,
    {word:'Ne kadar hazin bir çağda yaşıyoruz, bir önyargıyı ortadan kaldırmak atomu parçalamaktan daha güç.',author:'- Albert Einstein'} ,
    {word:'Bir kere sevdaya tutulmaya gör; ateşlere yandığının resmidir. ',author:'- Cahit Sıtkı Tarancı'},
    {word:'Hayat bir öyküye benzer, önemli olan yani eserin uzun olması değil, iyi olmasıdır. ',author:'- Seneca'},
    {word:'Beni mahveden şey; bana yalan söylemiş olman değil, sana bir daha inanmayacak olmamdır. ',author:'- Victor Hugo'},
    {word:'İyiliğinize inanılmasını istiyorsanız,ondan hiç söz etmeyin',author:'-  Blaise Pascal'} ,
    {word:'İnsanlar başaklara benzer.İçleri boşken başları havadadır, doldukça eğilirler.',author:' - Montaigne'},
    {word:'Konuşup konuşmamak bir şeyi değiştirmeyecekse, susmamak için bir neden yoktur.',author:'- Nuovo Cinema Paradiso'} ,
    {word:'İyiliğin bilgisine sahip olmayana bütün diğer bilgiler zarar verir.',author:'-  Montaigne'} ,
    {word:'Mutluluk her şeyden önce vücut sağlığındadır.',author:'- Curtis'} ,
    {word:'Şikayet ettiğiniz yaşam, belkide başkasının hayalidir.TolstoyBir araya gelmek bir başlangıçtır, beraberliği sürdürmek bir ilerleme…',author:''},
    {word:'Beraber çalışmaksa gerçek başarıdır. ',author:'- Henry Ford'},
    {word:'Hayatınızın kalitesini hayatınızdaki insanların kalitesi belirler.',author:' - J.Brown'},
    {word:'Kaptanın ustalığı deniz durgunken anlaşılmaz. ',author:'- Lukianos'},
    {word:'Bazen insan öyle özlenir ki; özlenen bilse, yokluğundan utanır.',author:'- Aziz Nesin'} ,
    {word:'Bilginin efendisi olmak için çalışmanın uşağı olmak şarttır. ',author:'- Honore de Balzac'},
    {word:'Planınız bir yıl içinse pirinç ekin, on yıl içinse ağaç dikin, yüz yıl için ise insanları eğitin.',author:'- Huang-Çe'} ,
    {word:'Yap gitsin! İnsan en çok hatalarından ders çıkartır.',author:'- Al Pacino'} ,
    {word:'Can paramparça ve ellerim, kelepçede, tütünsüz, uykusuz kaldım, terk etmedi sevdan beni…',author:'- Ahmet Arif'} ,
    {word:'Bir insanın hayatının ikinci yarısı, ilk yarıda kazanılan alışkanlıkların sürdürülmesinden ibarettir.',author:'- Dostoyevski'},
    {word:'İyi kararlar tecrübeden kaynaklanır.Tecrübeler ise kötü kararlardan…',author:'- Barry LePatner'},
    {word:'Demokrasi, hakkettiğimizden daha iyi yönetilmeyeceğimizi garanti eden bir sistemdir.',author:'- George Bernard Shaw'},
    {word:'Peşinden gidecek cesaretin varsa, bütün hayaller gerçek olabilir! ',author:'- Che Guevara'},
    {word:'Hakları ve zevkleri ellerinden alınan gençler, onların yerine daha gizli ve tehlikeli olanlarını koyar.',author:'- J.J.Rousseau'} ,
    {word:'Bütün sevgileri atıp içimden, varlığımı yalnız ona verdim ben, elverir ki bir gün bana derinden, ta derinden bir gün bana “Gel” desin.',author:'- Ahmet Kutsi Tecer'} ,
    {word:'Arkadaşlık kuvvetli bir bağdır.Paraya ihtiyaç olunca başvurulmazsa, ömür boyu sürer.',author:'- Mark Twain'},
    {word:'En kötü barış, en haklı savaştan daha iyidir.',author:' - Cicero'},
    {word:'Herkes tarafından doğru kabul edilen şeyler büyük olasılıkla yanlıştır.',author:' - Paul Valery'},
    {word:'Can paramparça ve eIIerim, keIepçede, tütünsüz, uykusuz kaIdım, terk etmedi sevdan beni…',author:''},
    {word:'Beni güzeI hatırIa.Sana unutuImaz geceIer bıraktım, sana en yorgun sabahIar, güIüşümü, gözIerimi, sonra sesimi bıraktım.',author:''},
    {word:'Sıradan öğretmen anIatır, iyi öğretmen açıkIar, yetenekIi öğretmen yapar ve gösterir, büyük öğretmen esin kaynağı oIur.',author:''},
    {word:'Kimse kimseyi unutmuyor ama asIa karşı tarafın istediği biçimde hatırIamıyor.',author:''},
    {word:'Farzet ki yazdıklarımı anlayabildin. Ya anlamadıkların. Ya yazıp yazıp sildiklerim. Ya yazamadıklarım…',author:''},
    {word:'Yüzüne gülecek kadar dost sandığın kişilerin aslında arkandan konuşacak kadar yüzsüz.',author:''},
    {word:'Bir insanın zekası verdiği cevaplardan değil sorduğu sorulardan belli olurmuş.',author:''},
    {word:'Her insan yanlış yapabilir ancak sadece büyük insanlar yanlışlarının farkına varabilir.',author:''},
    {word:'Hayatta asıl önemli olan şey istediğini almak değil. Aldıktan sonra onu hala isteyip istememektir.',author:''},
    {word:'Eğer dünya sana soğuk geliyorsa, onu ısıtmak için ateş yak.',author:'Lucy Larcom'},
    {word:'Birçok insan yirmi beş yaşında ölür ve yetmiş beşe kadar gömülmez.',author:'Benjamin Franklin'},
    {word:'Odaklanmak, hayır demekle ilgilidir.',author:'Steve Jobs'},
    {word:'Öğrenmeye devam eden herkes genç kalır.',author:'Henry Ford'} ,
    {word:'Kararlarınıza bağlı kalın, ancak yaklaşımınızda esnek kalın.',author:'Tony Robbins'} ,
    {word:'Aşk, hoşgörü ve alçakgönüllülük varsa dünya daha iyi olabilir. ',author:'Irena Sendler'},
    {word:'Kendinizi olumlu insanlarla çevirin.',author:'Melanie'} ,
    {word:'Arıza bulmayın, bir çare bulun.',author:'Henry Ford'},
    {word:'Bence toplumun ilk görevi adalettir.',author:'Alexander Hamilton'},
    {word:'Düşünme: ruhun kendisi ile konuşmasıdır.',author:'Platon'} ,
    {word:'Dua, insanın en büyük gücüdür!',author:'W.Clement Stone'} ,
    {word:'En iyi yol dosdoğru gidendir.',author:'Robert Frost'},
    {word:'Kendinizde var olana sadık olun.',author:'Andre Gide'},
    {word:'Sağırlık kulakta değil; akıldadır.',author:'Marlee Matlin'},
    {word:'Kariyer yapmak harika! Ama soğuk gecelerde kariyerinize sarılıp yatamazsınız.',author:'- Marilyn Monroe'} ,
    { word:'Aşk Hatalara karşı Daima Kördür, Daima Mutluluklara Meyillidir, Kanun Tanımaz, Kanatlıdır ve tutuklanamaz.Kafaların Bütün Zincirlerini Kırar geçer.',author:'- William BIake'} ,
    {word:'Mutluluğun formülü, gerektiğinde önemsiz şeylerle meşgul olabilmektedir. ',author:'- Edward Newton'},
    {word:'Başarının sırrını bilmiyorum ama başarızılığın yolu herkesi memnun etmeye çalışmaktan geçer.',author:' - Bill Cosby'},
    {word:'Eğer insanlar hiç salakça şeyler yapmasaydı, akıllıca işler yapılamazdı. ',author:'- Ludwig Wittgenstein'},
    {word:'Biri sizi bir defa aldatırsa suç onundur.İkinci defa aldanırsanız bilin ki suç sizindir. ',author:'- Sarah Berhardt'},
    {word:'Zeki bir insan yalnızlıkta, düşünceleri ve hayal gücüyle mükemmel bir eğlenceye sahiptir. ',author:'- Schopenhauer'} ,
    {word:'Açalım yüreğimizin kapılarını sonuna kadar, sevelim sevelim sevelim, sevebileceğimiz kadar.',author:' - Bedri Rahmi Eyüboğlu'},
    {word:'İdealler yıldızlara benzer. Onlara ulaşamazsınız, ama size yol gösterirler.',author:'- Waldo Emerson'},
    {word:'Her şeyi elde edebilirsin. Ama aynı anda değil! ',author:'- Oprah Winfrey'},
    {word:'Ona şefkatle eğilirken, pır diye uçtu birden, kırık sandığım kanatlarındaki sahtelik ve inancımla birlikte. ',author:'- Ahmet Muhip Dranas'},
    {word:'Ümit, mutluluktan alınmış bir miktar borçtur.',author:'-  Joseph Joubert'},
    {word:'Aşk dediğin nedir ki, tenden bedenden sıyrık, çocukların içinde, yaşadığı bir çığlık. ',author:'- Ahmet Hamdi Tanpınar'},
    {word:'Gömleğin ilk düğmesi yanlış iliklenince, diğerleri de yanlış gider. ',author:'- C.Bruno'},
    {word:'Bilgili bir ahmak, cahil bir ahmaktan daha çok ahmaktır. ',author:'- Moliere'},
    {word:'Yaşamak değil, beni bu telaş öldürecek. ',author:'- Özdemir Asaf'},
    {word:'Tanrı kuşları sevdi ve ağaçları yarattı.İnsan kuşları sevdi ve kafesleri yarattı. ',author:'-  Jacques Deval'},
    {word:'Hayat bazen insanları, birbirleri için ne kadar çok şey ifade ettiklerini anlasınlar diye ayırır.',author:'- P.Coelho'} ,
    {word:'Uzman, dar bir alanda yapılabilecek tüm hataları yapmış kişiye denir.',author:'- Niels Bohr'},
    {word:'Sen ne kadar kalsan da geliyorsun benimle.Ben ne kadar gitsem de kalıyorum seninle.',author:' - Shakespeare'},
    {word:'Yalnızca bir deli, suyun derinliğini iki ayağıyla anlamaya kalkar. ',author:'- Afrika Atasözü'},
    {word:'Öyle bir seveceksin ki, yüreğinden kimse ayıramayacak.Ve öyle birini seveceksin ki, seni gözleriyle bile aldatmayacak.',author:'- Can Yücel'} ,
    {word:'Nankör insan, her şeyin fiyatını bilen fakat hiçbir şeyin değerini bilmeyen kimsedir.',author:' - Oscar Wilde'},
    {word:'Dünyanın gerçek gizemi görünmeyende değil, görünendedir.',author:'- Oscar Wilde'},
    {word:'Kimse kimseyi unutmuyor ama asla karşı tarafın istediği biçimde hatırlamıyor.',author:'- Tezer Özlü'},
    {word:'Аşk, dаvаyа bеnzеr, cеfа çеkmеk dе şаhidе. Şаhidin yoksа dаvаyı kаzаnаmаzsın ki. ',author:'Mevlana'},
    {word:'Dеdilеr ki; Gözdеn ırak olan gönüldеn dе ırak olur.Dеdim ki; Gönül’е girеn gözdеn ırak olsa nе olur. ',author:'Mevlana'},
    {word:'Aşk, öylе еngin bir dеnizdir ki, nе bаşlаngıcı nе dе sonu vаrdır. ',author:'Mevlana'},
    {word:'Gеrеk yok hеr sözü laf ilе bеyana, bir bakış bin söz еdеr bakıştan anlayana. ',author:'Mevlana'},
    {word:'Aşk acısı taşımayan yürеk; ya dеliyе aittir, ya ölüyе. ',author:'Mevlana'},
    {word:'Sеn böylе güzеlkеn bаnа söz düşmеz.Bаkmа böylе yаzılаr yаzdığımа, bеn аslındа Oku! Еmrinе аmаdе sеni okuyorum sеvgili. ',author:'Mevlana'},
    {word:'Bırakacağın еli hiç tutma, tutacağın еli isе hiç bırakma.Sahtе sеvgilеrе gül olmaktansa, gеrçеk sеvgilеrе dikеn ol! ',author:'Mevlana'},
    {word:'Minarеdеn düşеnin parçası bulunur, bulunur da; Gönüldеn düşеnin parçası bulunmaz. ',author:'Mevlana'},
    {word:'Еy Gönlümün sol yarısı, Aklıma koydum sеni, aklım almadı.Yürеğimе bıraktım, sana doymadı. ',author:'Mevlana'},
    {word:'Acı, acıyla iyileşir.Aşk ise daha büyük bir aşkla.',author:'Mevlana'},
    {word:'Allah(c.c)’a ulaşacak birçok yol var.Ben Aşk’ı seçtim.',author:'Mevlana'},
    {word:'Aşk, her şeydedir ama hiçbir şeyde görünmez.',author:'Mevlana'},
    {word:'Ayağına batan dikenler, aradığın gülün habercisidir.',author:'Mevlana'},
    {word:'Uğruna fedakârlık yapmadığın sevgiyi, yüreğinde taşıyıp da kendine yük etme.',author:'Mevlana'},
    {word:'Asıl yar yaradandır, gerisi yaralayandır.',author:'Mevlana'},
    {word:'Zor diyorsun, zor olacak ki imtihan olsun.',author:'Mevlana'},
    {word:'Yürek yorulunca ter gözden akar.',author:'Mevlana'},
    {word:'Yüreğimiz kıymet bilene emanet.',author:'Mevlana'},
    {word:'Kalp deniz, dil kıyıdır. Denizde ne varsa kıyıya o vurur.',author:'Mevlana'},
    {word:'Üzülme herkes ölür kimi toprağa gömülür, kimi yüreğe.',author:'Mevlana'},
    {word:'Ya olduğun gibi görün, ya göründüğün gibi ol.',author:'Mevlana'},
    {word:'Bize gözün değil, gönlün gördüğü yürek gerek.',author:'Mevlana'},
    {word:'Dost acı söyleyen değildir. Acıyı tatlı söyleyebilendir.',author:'Mevlana'},
    {word:'Kapı açılır sen yeter ki vurmayı bil.Ne zaman? Bilmem.Yeter ki o kapıda durmayı bil.',author:'Mevlana'},
    {word:'Ve ben; dilek tutmadım hiç.Hep dua ettim: ‘ömrün ömrüme nasip olsun’ diye.',author:'Mevlana'},
    {word:'Minareden düşenin parçası bulunur da, gönülden düşenin parçası bulunmaz.',author:'Mevlana'},
    {word:'Aşk, altın değildir, saklanmaz.Aşkın bütün sırları meydandadır.',author:'Mevlana'},
    {word:'Birini seviyorsanız, onu Allah’tan isteyin. Kalpler Allah’ın elindedir.',author:'Mevlana'},
    {word:'Öyle bir ‘yâr’ sev ki evladım; elinde su tasıyla, iftarı bekleyen oruçlu gibi beklesin seni.',author:'Mevlana'},
    {word:'Güzeli güzel yapan ‘edep’tir, edep ise güzeli sevmeye sebeptir.',author:'Mevlana'},
    {word:'Ey gönül. Ateş için rüzgâr ne ise, aşk için de ayrılık öyledir; küçük olanı söndürür, büyük olanı ise daha da güçlendirir ve iyi bil ki, ey gönül.Aşk; ateşten bir denizi, mumdan kayıkla geçmektir, yanıp kül olmadan asla geçemezsin.',author:'Mevlana'},
    {word:'Aşk öyle engin bir denizdir ki, ne kenarı vardır, ne de ucu bucağı.',author:'Mevlana'},
    {word:'Aşk bir uçurumdan düşmek gibidir, bunun için sevgiliye “yar” denilir.',author:'Mevlana'},
    {word:'Aşk, her şeydedir ama hiçbir şeyde görünmez.',author:'Mevlana'},
    {word:'Gözyaşının bile görevi varmış; ardından gelecek gülümseme için temizlik yaparmış.',author:'Mevlana'},
    {word:'Hadi yaramı sarmaya merhemin yok. Yalandan da olsa gönül alamaz mısın?',author:'Mevlana'},
    {word:'Aşk; sandığın kadar değil, yandığın kadardır.',author:'Mevlana'}




];